security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\KundInloggning:
            algorithm: sha512
    providers:
        app_user_provider:
            entity:
                class: App\Entity\KundInloggning
                property: emailAdress
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: false
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
            guard:
                authenticators:
                  - App\Security\LoginFormAuthenticator
    access_control:
        - { path: ^/medlemmar/registrering, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/medlemmar/inloggning, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/medlemmar/registrera, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
