site_name: Biograf-projektet
site_url: https://docs.biograf.edu.alexvnilsson.se
site_author: Alex V. Nilsson
edit_uri: ''
copyright: '2020'
social:
  website: https://alexvnilsson.se
repo_url: https://github.com/alexvnilsson-edu/biograf_app
repo_name: biograf_app
theme:
  name: material
  language: sv
  custom_dir: overrides
  font:
    text: Open Sans
    code: Fira Code
  palette:
    primary: red
    accent: blue
  features:
    - tabs
    - navigation.expand
extra_css:
  - _stylesheets/root.css
  - _stylesheets/extra.css
  - _stylesheets/highlight.css
  - _stylesheets/details.css
  - _stylesheets/typography.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - def_list
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.emoji
  - pymdownx.magiclink:
      repo_url_shortener: true
  - markdown_include.include:
      base_path: docs/
  - pymdownx.inlinehilite:
      css_class: 'code_inline'
      style_plain_text: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
  - toc:
      permalink: false
# plugins:
#   - awesome-pages:
#       collapse_single_pages: false
nav:
  - Komma igång:
    - Första stegen:
      - Initiera projektet: guidelines/first-steps/init-project.md
    - Databas:
      - guidelines/database/README.md
      - guidelines/database/entities.md
  - Symfony:
    - Symfony CLI:
      - symfony/cli/index.md
      - symfony/cli/symfony-composer.md
  - Referenser:
    - Översikt: ./reference-overview.md
    - Controller:
      - IndexController: reference/Controller/IndexController.md
      - MemberController: reference/Controller/MemberController.md
      - SecurityController: reference/Controller/SecurityController.md
    - Entity:
      - Auditorium: reference/Entity/Auditorium.md
      - Cinema: reference/Entity/Cinema.md
      - City: reference/Entity/City.md
      - Movie: reference/Entity/Movie.md
      - MovieCover: reference/Entity/MovieCover.md
      - MovieGenre: reference/Entity/MovieGenre.md
      - User: reference/Entity/User.md
    - Form:
      - Type:
        - UserType: reference/Form/Type/UserType.md
    - Security:
      - LoginFormAuthenticator: reference/Security/LoginFormAuthenticator.md
    - Service:
      - MemberManager: reference/Service/MemberManager.md
      - MovieManager: reference/Service/MovieManager.md