site_name: Biograf-projektet
site_url: https://docs.biograf.edu.alexvnilsson.se
site_author: Alex V. Nilsson
edit_uri: ""
copyright: "2020"
social:
    website: https://alexvnilsson.se

# Käll-repo
repo_url: https://github.com/alexvnilsson-edu/biograf_app
repo_name: biograf_app

# MkDocs tema
theme:
    name: material
    language: sv
    custom_dir: overrides
    font:
        text: Open Sans
        code: Fira Code
    palette:
        primary: hsl(4, 65%, 49%)
        accent: blue
    features:
        - tabs
        - navigation.expand

# Extra CSS-filer eller link-element.
extra_css:
    - _stylesheets/root.css
    - _stylesheets/print.css
    - _stylesheets/extra.css
    - _stylesheets/highlight.css
    - _stylesheets/details.css
    - _stylesheets/typography.css

# Markdown-tillägg
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - footnotes
    - def_list
    - attr_list
    - pymdownx.tabbed
    - pymdownx.smartsymbols
    - pymdownx.emoji
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink:
        repo_url_shortener: true
    - markdown_include.include:
        base_path: docs/
    - pymdownx.inlinehilite:
        css_class: "code_inline"
        style_plain_text: true
    - pymdownx.highlight:
        use_pygments: true
        linenums: false
    - toc:
        permalink: false

# Plugins
plugins:
    - awesome-pages:
        collapse_single_pages: true