name: docs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCS_DIR: docs
      DOCS_REFERENCE_DIR: docs/reference
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - name: Remove composer.json and composer.lock
        run: |
          rm -f -- composer.json composer.lock
      - name: Install dependencies
        uses: php-actions/composer@v2
        with:
          command: require clean/phpdoc-md
      - name: Clean up docs output (${{ env.DOCS_DIR }}/${{ env.DOCS_REFERENCE_DIR }}).
        run: |
          rm -rf ${{ env.DOCS_DIR }}/${{ env.DOCS_REFERENCE_DIR }}
          mkdir -p ${{ env.DOCS_DIR }}/${{ env.DOCS_REFERENCE_DIR }}
      - run: |
          vendor/bin/phpdoc-md
          cd ${{ env.DOCS_DIR }}
          mkdocs gh-deploy --force